// tables
export * from './affiliates/tables'
export * from './agents/tables'
export * from './auth/tables'
export * from './bookmarks/tables'
export * from './communities/tables'
export * from './events/tables'
export * from './notifications/tables'
export * from './orders/tables'
export * from './settings/tables'
export * from './subgraph/tables'
export * from './sumsub/tables'
export * from './waitlist/tables'

// relations
export * from './affiliates/relations'
export * from './auth/relations'
export * from './bookmarks/relations'
export * from './communities/relations'
export * from './events/relations'
export * from './notifications/relations'
export * from './orders/relations'
